# Source: gitlab/charts/gitlab/charts/webservice/templates/ingress.yaml
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: gitlab-webservice-default
  namespace: gitlab
  labels:
    app: webservice
    release: gitlab
    gitlab.com/webservice-name: default
  annotations:
    cert-manager.io/cluster-issuer: "my-ca-issuer"
spec:
  rules:
    - host: gitlab.tanzu.demo
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitlab-webservice-default
                port: 
                  number: 8181
  tls:
    - hosts:
      - gitlab.tanzu.demo
      secretName: gitlab-gitlab-tls
---
# Source: gitlab/charts/minio/templates/ingress.yaml
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: gitlab-minio
  namespace: gitlab
  labels:
    app: minio
    release: gitlab
    
  annotations:
    cert-manager.io/cluster-issuer: "my-ca-issuer"
spec:
  
  rules:
    - host: minio.tanzu.demo
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitlab-minio-svc
                port: 
                  number: 9000
  tls:
    - hosts:
      - minio.example.com
      secretName: gitlab-minio-tls